config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'books#search'

  resources :users do
    resources :books do
      collection do
        get 'search'
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :user_shelves
  has_many :users, through: :user_shelves

  validates :isbn, uniqueness: true, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, authentication_keys: [:login]

  attr_accessor :login

  has_many :user_shelves
  has_many :books, through: :user_shelves

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end
end

app/models/user_shelf.rb
class UserShelf < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def index
    @books = current_user.books
  end

  def search
    @books = BooksFinder.new(params[:option], params[:term]).find
  end

  def show
    @book = Book.find(params[:id])
  end

  def create
    book = GoogleBooks.search(params[:isbn]).first
    current_user.books.create(
      title: book.title,
      isbn: book.isbn,
      image_link: book.image_link
    )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/_list.html.erb
<%- @books.to_a.in_groups_of(4) do |group| %>
  <div class="row">
    <% group.compact.each do |book| %>

      <div class="col-lg-3 col-md-4 col-sm-6 book-item">
        <div class="card h-100">
          <% if book.image_link.present? %>
              <%= image_tag(book.image_link) %>
          <% else %>
              <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
          <% end %>

          <div class="card-body">
            <h4 class="card-title">
              <a href="#"><%= book.title %></a>
            </h4>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/books/index.html.erb
<%= render 'list' %>

app/views/books/search.html.erb
<h1 class="my-4">Поиск
  <small>по полкам пользователей</small>
</h1>

<div class="row">
  <div class="col-md-12" id="search-field">
    <%= form_tag(search_user_books_path(current_user), method: :get) do %>

      <div class="input-group add-on">
        <%= text_field_tag :term, '', placeholder: 'Search for...', class: 'form-control', id: 'srch-term' %>

        <div class="input-group-btn">
          <%= submit_tag 'Search', class: 'btn btn-default' do %>
            <i class="glyphicon glyphicon-search"></i>
          <% end %>
        </div>
      </div>

      <label class='checkbox-inline'>
        <%= radio_button_tag :option, :user, true %>
        By ebb user
      </label>
      <label class='checkbox-inline'>
        <%= radio_button_tag :option, :web, params[:option] == 'web' ? true : false %>
        In web
      </label>
    <% end %>
  </div>
</div>

<% if params[:option] == 'web' %>
  <%- @books.to_a.in_groups_of(4) do |group| %>
    <div class="row">
      <% group.compact.each do |book| %>

        <div class="col-lg-3 col-md-4 col-sm-6 book-item">
          <div class="card h-100">
            <% if book.image_link.present? %>
              <%= image_tag(book.image_link(zoom: 2)) %>
            <% else %>
              <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
            <% end %>

            <div class="card-body">
              <h4 class="card-title">
                <a href="#"><%= book.title %></a>
              </h4>
              <% if current_user.books.pluck(:isbn).include?(book.isbn) %>
                <div>
                  Уже добавлена на полку
                </div>
              <% else %>
                <div>
                  <%= link_to 'У меня такая есть', user_books_path(current_user, isbn: book.isbn), method: :post, class: 'btn btn-success' %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>

  <% else %>
    <%- Book.all.to_a.in_groups_of(4) do |group| %>
      <div class="row">
        <% group.compact.each do |book| %>
          <div class="col-lg-3 col-md-4 col-sm-6 book-item">
            <div class="card h-100">
              <% if book.image_link.present? %>
                <%= image_tag(book.image_link) %>
              <% else %>
                <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
              <% end %>

              <div class="card-body">
                <h4 class="card-title">
                  <a href="#"><%= book.title %></a>
                </h4>
                <div> На полке у <%= book.users.pluck(:username).join(',') %> </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
<% end %>

app/views/books/show.html.erb
<div>
  <div class="title"><%= link_to @book.title, user_book_path(current_user, @book) %></div>
  <% if @book.image_link.present? %>
      <%= image_tag(@book.image_link) %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ebbbookcrossing</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

  </head>

  <body>
    <%= render 'layouts/shared/navbar' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <a class="navbar-brand" href=<%= root_path %>>Ebbbookscrossing</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href=<%= root_path %>>Home
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Contact</a>
        </li>

        <% if current_user %>
          <li class="nav-item">
            <%= link_to 'Sign Out', destroy_user_session_path, class: 'nav-link', method: :delete %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>